### ISSUE TITLE
Mise à jour des données ?

### ISSUE THREAD

**Issue by pedrom34** [arbre-app/insee-deces-front#1]
Bonjour,

Une mise à jour des données est elle prévue ?

Merci !

**Comment by FlorianCassayre** [comment]
Bonjour,

Je souhaiterais intégrer quelques changements dans [le backend](https://github.com/FlorianCassayre/insee-db) avant cela, je vais essayer de le faire en fin de semaine.

**Comment by FlorianCassayre** [comment]
J'ai pris un peu de retard mais la mise à jour a été effectuée hier avec les données d'octobre. J'ai pu automatiser une partie du processus ce qui devrait me permettre de le réaliser plus régulièrement.

**Comment by pedrom34** [comment]
Chapeau ! Merci beaucoup ! 👍
